### ISSUE TITLE
Tx amount input decimals are inconsistent

### ISSUE THREAD

**Issue by sisou** [nimiq/safe#104]
When full decimals are _not_ activated, the MAX button in the send-tx modal still puts up to 5 decimals in the input.

However, when then choosing a contact from the contact list and then trying to send, the input limits trigger and the submitting fails.

We should probably just disable the decimals limit for the input and just leave it at 5 always.

**Comment by Bettelstab** [comment]
Disable the limit sounds good for now.

**Comment by Bettelstab** [comment]
Solved by https://github.com/nimiq/elements/commit/56bffcc90cede157ed3e5d3225b7b84ba1f28512
