### ISSUE TITLE
selected account should not be visible in selection list

### ISSUE THREAD

**Issue by Bettelstab** [nimiq/safe#13]

**Comment by Bettelstab** [comment]
Solved by https://github.com/nimiq/elements/commit/65363f207321df84d9f2e68b445d695e07240f55

**Comment by sisou** [comment]
Undone by https://github.com/nimiq/elements/commit/9846e580be64a08aaa1f309ac2ebc75fcc194003 because of exceptions

**Comment by Bettelstab** [comment]
https://github.com/nimiq/elements/commit/05809aac788971aa07e82b098ea3bd93990f46d1
