### ISSUE TITLE
Address QR codes not working on Trust Wallet

### ISSUE THREAD

**Issue by PanoramicRum** [nimiq/safe#153]
**How to reproduce**: In the safe click the QR code and scan the QR code with Trust wallet.
**Current result**: The address in the Trust wallet app is safe.nimiq.com
**Expected result**: The NIM address is copied to the Trust wallet app

**Comment by sisou** [comment]
There are two QR codes for an address. I agree it's confusing.

The one you talk about is in the `Receive` window, were you create Nimiq Payment Request Links, which only work in the Safe.

In the `Address` window you get a QR code that only includes the address.

![image](https://user-images.githubusercontent.com/1828163/68994805-ac54d980-084c-11ea-9bdd-8f778ae106d8.png)

**Comment by sisou** [comment]
We will change the content of the QR code to work in Trust Wallet.

**Comment by sisou** [comment]
Progress! :rocket:
Nimiq URI encoding PR here: https://github.com/nimiq/nimiq-utils/pull/32

**Comment by danimoh** [comment]
This can be closed as of 791686fb1be0318699d8f1c326abb4b769b9553b I think.
Please reopen, if this issue is not resolved yet.
