### ISSUE TITLE
Use normal ports like 443 80 for websockets

### ISSUE THREAD

**Issue by lucsoft** [nimiq/safe#157]
most ports get blocked normaly

**Comment by sisou** [comment]
If you mean the websockets that the Nimiq Core Browser Client creates to other nodes in the network, then that is something that we can only _suggest_ to people, not enforce. Every node operator is individually responsible for the port they use to operate their node.

We can however influence what ports our seed nodes use. I will bring it up in the team.

**Comment by lucsoft** [comment]
thanks
