### ISSUE TITLE
Hierarchical Deterministic Key Derivation in the Safe?

### ISSUE THREAD

**Issue by sisou** [nimiq/safe#40]

**Comment by trishmapow** [comment]
I support this. Would be nice to have a lot of addresses under one private key for privacy and convenience reasons. Currently creating a separate wallet takes too long especially because seed words cannot be copy pasted.

**Comment by Bettelstab** [comment]
It's in development and will be included in the upcoming versions of our ecosystem apps :)

**Comment by Bettelstab** [comment]
However, although it will be accessible through Nimiq Safe, all the logic will be contained here: https://github.com/nimiq/accounts and here: https://github.com/nimiq/keyguard-next

**Comment by sisou** [comment]
I created this issue when I thought about key derivation, not knowing that it was planned to be included in the new Keyguard by the core team anyway. Since it's now already in @nimiq/core released and coming in the new Keyguard, this issue is closed with #fixed.
