### ISSUE TITLE
Mainnet/Testnet Switch in Safe

### ISSUE THREAD

**Issue by sisou** [nimiq/safe#5]
The Safe needs to have an UI feature to enable switching between connecting to the mainnet or a testnet.

**Comment by Bettelstab** [comment]
Daniel and me think this is not a good idea to give users this possibility. Interested people should be able to download and build their own version. Later we could setup dedicated test versions of safe, wallet... to test new features with the testnet.

**Comment by sisou** [comment]
Metamask also offers this feature.


via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=9.8.211&pv=7.0&source=email_footer_2] On Mon, Mar 12, 2018 at 4:14pm, Bettelstab < notifications@github.com [notifications@github.com] > wrote:
Daniel and me think this is not a good idea to give users this possibility. Interested people should be able to download and build their own version. Later we could setup dedicated test versions of safe, wallet... to test new features with the testnet.

**Comment by sisou** [comment]
"Implemented" by using different domains: safe.nimiq.com vs safe.nimiq-testnet.com.
