### ISSUE TITLE
Address count in account selector does not update after adding an address

### ISSUE THREAD

**Issue by Bettelstab** [nimiq/safe#53]
After reloading, it shows the right number.

**Comment by Bettelstab** [comment]
Solved by https://github.com/nimiq/safe/commit/13bc4ead9d8b15d305abf4651b0159ce9e1ca6d4

**Comment by sisou** [comment]
Your "solution" was then fixed by cf7ebeb23fce63426740ee59d5eb495354d64763, ecb1415cadcc44302e94b3448b07da101bf3e17c and bc993e5aa08c9296f03e6bee618ce9548696e924. Well done.

**Comment by Bettelstab** [comment]
Besides keeping naming consistent, what was the problem with it?

**Comment by sisou** [comment]
The sort function did not sort, the `wallet.walletId` is not `LEGACY` but the actual hex wallet ID, `wallet.isLegacy` is the only indicator.

**Comment by Bettelstab** [comment]
I see. Sorry :( This is why I love typescript :D
