### ISSUE TITLE
Amount value in Send is sometimes prefilled with 0, which  removes option of clicking 'max'

### ISSUE THREAD

**Issue by Bettelstab** [nimiq/safe#55]

**Comment by sisou** [comment]
Do you think, adding
```js
if (!amount) amount = '';
```
before https://github.com/nimiq/elements/blob/master/x-send-transaction/x-send-transaction.js#L137 is enough? That would set it from 0 to an empty string. May be enough?

**Comment by Bettelstab** [comment]
Might suffice indeed.

**Comment by Bettelstab** [comment]
Should be solved by https://github.com/nimiq/elements/commit/5ba985d070cda707deddaa532e7a6acf4d185c32
