### ISSUE TITLE
Unable to send NIM to contacts

### ISSUE THREAD

**Issue by Eligioo** [nimiq/safe#82]
First you send some NIM to an address (not by clicking on one of your contacts).
Then click on one of you contacts. The send NIM modal will appear with your contact address prefilled. But the Send button stays on Loading from the first transaction.

https://www.loom.com/share/53362d062dda438ca20d4cc2f17de6b3

**Comment by Bettelstab** [comment]
Fixed by https://github.com/nimiq/elements/commit/0d8080afe55b6a580ff5bc4e6ce9d98b55c0bec0
