### ISSUE TITLE
Sometimes address balances become negative

### ISSUE THREAD

**Issue by sisou** [nimiq/safe#99]
![NIMIQ_HACKED2](https://user-images.githubusercontent.com/1828163/57587714-a2eb5d00-7509-11e9-9900-64cfa3911ecb.png)

![NIM_HACKED](https://user-images.githubusercontent.com/1828163/57587703-78010900-7509-11e9-9893-fe0701c88aad.png)

**Comment by sisou** [comment]
This has something to do with pending transactions, syncing the balance, and the way the balance of accounts is reduced when transactions are pending.

**Comment by Bettelstab** [comment]
Hopefully solved by https://github.com/nimiq/nano-api/commit/2aaea28a156fe71cd772d6b2c2d4b8dc678776ab
